# Generated by Django 2.2.2 on 2019-06-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='excersise_number',
            new_name='exercise_number',
        ),
    ]
